### ISSUE TITLE
Feature Request: Allow Peerd to execute commands on up/down

### ISSUE THREAD

**Issue by terefang** [skx/sysbox#44]
hello

having a simple peerd is nice but having to constantly track the state-file might be problematic.

it would be nice to allow peerd to execute commands on up/down events giving them on the command-line like:

```
peerd -ip 1.2.3.4 1.2.3.1 -onup="/path/to/command1 options {}" -ondown="/path/to/command2 options {}"
```

thx in advance

**Comment by skx** [comment]
Another easy/obvious suggestion.  Thanks very much!

I'll handle this.  Presumably the "{}" would be replaced by the new peer IP?
